name: Continuous Deployment to Production

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Using Node.js 20.X
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
